# Generated by Django 3.2.4 on 2021-08-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stock/static/images'),
        ),
    ]
