# Generated by Django 3.2.4 on 2021-08-23 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_contacts_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stock/static/'),
        ),
    ]
